name: Build Prod
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Build Prod

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Build Project
              run: |
                  npm install -g yarn
                  yarn
                  yarn build

            - name: Copy Files
              uses: burnett01/rsync-deployments@5.2
              with:
                  switches: -avzr --delete
                  path: dist
                  remote_path: /home/${{ secrets.SSH_USERNAME }}/catalyst-school-frontend
                  remote_host: ${{ secrets.SSH_HOST }}
                  remote_user: ${{ secrets.SSH_USERNAME }}
                  remote_key: ${{ secrets.SSH_KEY }}
